package com.example.myplayer

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.BufferedReader
import java.net.HttpURLConnection
import java.net.URL

data class SubtitleTrack(
    val languageCode: String,
    val displayName: String,
    val url: String,
    val isAutoGenerated: Boolean
)

data class VideoQuality(
    val label: String,
    val height: Int,
    val url: String,
    val isVideoOnly: Boolean
)

object YouTubeStream {

    private const val TAG = "YouTubeStream"

    // ★ Invidious 공개 인스턴스 (fallback용)
    private val INVIDIOUS_INSTANCES = listOf(
        "https://inv.nadeko.net",
        "https://invidious.nerdvpn.de",
        "https://iv.melmac.space",
        "https://invidious.f5.si",
        "https://invidious.privacyredirect.com",
        "https://yt.artemislena.eu",
        "https://invidious.reallyaweso.me"
    )

    // ★ Piped 공개 인스턴스
    private val PIPED_INSTANCES = listOf(
        "https://pipedapi.kavin.rocks",
        "https://pipedapi.adminforge.de",
        "https://api.piped.private.coffee",
        "https://pipedapi.reallyaweso.me",
        "https://piped-api.lunar.icu"
    )

    data class StreamResult(
        val videoUrl: String?,
        val audioUrl: String?,
        val muxedUrl: String?,
        val title: String,
        val channelName: String,
        val description: String,
        val debug: String,
        val subtitles: List<SubtitleTrack> = emptyList(),
        val qualities: List<VideoQuality> = emptyList(),
        val audioUrlBest: String? = null,
        val isLive: Boolean = false
    ) {
        val hasAny: Boolean
            get() = muxedUrl != null || videoUrl != null || audioUrl != null
    }

    suspend fun extract(videoId: String): StreamResult = withContext(Dispatchers.IO) {
        val sb = StringBuilder()

        // ★ 1차: Invidious
        val inv = tryInvidious(videoId, sb)
        if (inv.hasAny) return@withContext inv

        // ★ 2차: Piped
        val piped = tryPiped(videoId, sb)
        if (piped.hasAny) return@withContext piped

        sb.append("모든 instance 실패\n")
        StreamResult(null, null, null, "", "", "", sb.toString())
    }

    // ═══════════════════════════════════════════
    // Invidious
    // ═══════════════════════════════════════════
    private suspend fun tryInvidious(videoId: String, sb: StringBuilder): StreamResult =
        withContext(Dispatchers.IO) {
            for (instance in INVIDIOUS_INSTANCES) {
                try {
                    val url = URL("$instance/api/v1/videos/$videoId")
                    val conn = url.openConnection() as HttpURLConnection
                    conn.connectTimeout = 8000
                    conn.readTimeout = 12000
                    conn.setRequestProperty("User-Agent", "Mozilla/5.0")
                    conn.setRequestProperty("Accept", "application/json")
                    CookieUtil.apply(conn)

                    if (conn.responseCode !in 200..299) {
                        sb.append("inv $instance: HTTP ${conn.responseCode}\n")
                        continue
                    }

                    val text = conn.inputStream.bufferedReader().use(BufferedReader::readText)
                    val json = JSONObject(text)

                    val title = json.optString("title", "")
                    val author = json.optString("author", "")
                    val desc = json.optString("description", "")
                    val isLive = json.optBoolean("liveNow", false)
                    if (isLive) {
                        sb.append("inv $instance: live skip\n")
                        continue
                    }

                    // adaptiveFormats (오디오/비디오)
                    var audioUrl: String? = null
                    var audioBitrate = 0
                    var videoUrl: String? = null
                    var videoHeight = 0
                    val qualities = mutableListOf<VideoQuality>()

                    val formats = json.optJSONArray("adaptiveFormats")
                    if (formats != null) {
                        for (i in 0 until formats.length()) {
                            val f = formats.getJSONObject(i)
                            val type = f.optString("type", "")
                            val u = f.optString("url", "")
                            if (u.isBlank()) continue

                            if (type.startsWith("audio/")) {
                                val br = f.optInt("bitrate", 0)
                                if (br > audioBitrate) {
                                    audioBitrate = br
                                    audioUrl = u
                                }
                            } else if (type.startsWith("video/")) {
                                val h = f.optInt("height", 0)
                                if (h > 0) {
                                    qualities.add(VideoQuality("${h}p", h, u, true))
                                }
                                if (h > videoHeight) {
                                    videoHeight = h
                                    videoUrl = u
                                }
                            }
                        }
                    }

                    // muxed (formatStreams)
                    var muxed: String? = null
                    val formatStreams = json.optJSONArray("formatStreams")
                    if (formatStreams != null && formatStreams.length() > 0) {
                        muxed = formatStreams.getJSONObject(0).optString("url", null)
                    }

                    // 자막
                    val subs = mutableListOf<SubtitleTrack>()
                    val captions = json.optJSONArray("captions")
                    if (captions != null) {
                        for (i in 0 until captions.length()) {
                            val c = captions.getJSONObject(i)
                            val lang = c.optString("languageCode", "")
                            val label = c.optString("label", lang)
                            val u = c.optString("url", "")
                            if (u.isNotBlank() && lang.isNotBlank()) {
                                // Invidious 자막 url은 상대경로일 수 있음
                                val fullUrl = if (u.startsWith("http")) u else "$instance$u"
                                subs.add(SubtitleTrack(lang, label, fullUrl, false))
                            }
                        }
                    }

                    if (audioUrl != null || videoUrl != null || muxed != null) {
                        sb.append("inv 성공: $instance\n")
                        return@withContext StreamResult(
                            videoUrl = videoUrl,
                            audioUrl = audioUrl,
                            muxedUrl = muxed,
                            title = title,
                            channelName = author,
                            description = desc,
                            debug = sb.toString(),
                            subtitles = subs,
                            qualities = qualities.sortedByDescending { it.height },
                            audioUrlBest = audioUrl,
                            isLive = false
                        )
                    }

                    sb.append("inv $instance: URL 없음\n")
                } catch (e: Exception) {
                    sb.append("inv $instance: ${e.message?.take(60)}\n")
                }
            }
            StreamResult(null, null, null, "", "", "", sb.toString())
        }

    // ═══════════════════════════════════════════
    // Piped
    // ═══════════════════════════════════════════
    private suspend fun tryPiped(videoId: String, sb: StringBuilder): StreamResult =
        withContext(Dispatchers.IO) {
            for (instance in PIPED_INSTANCES) {
                try {
                    val url = URL("$instance/streams/$videoId")
                    val conn = url.openConnection() as HttpURLConnection
                    conn.connectTimeout = 8000
                    conn.readTimeout = 12000
                    conn.setRequestProperty("User-Agent", "Mozilla/5.0")
                    conn.setRequestProperty("Accept", "application/json")
                    CookieUtil.apply(conn)

                    if (conn.responseCode !in 200..299) {
                        sb.append("piped $instance: HTTP ${conn.responseCode}\n")
                        continue
                    }

                    val text = conn.inputStream.bufferedReader().use(BufferedReader::readText)
                    val json = JSONObject(text)

                    val title = json.optString("title", "")
                    val author = json.optString("uploader", "")
                    val desc = json.optString("description", "")

                    var audioUrl: String? = null
                    var videoUrl: String? = null
                    var videoHeight = 0
                    val qualities = mutableListOf<VideoQuality>()

                    val audioStreams = json.optJSONArray("audioStreams")
                    if (audioStreams != null && audioStreams.length() > 0) {
                        // 가장 높은 bitrate
                        var br = 0
                        for (i in 0 until audioStreams.length()) {
                            val f = audioStreams.getJSONObject(i)
                            val b = f.optInt("bitrate", 0)
                            val u = f.optString("url", "")
                            if (u.isNotBlank() && b > br) {
                                br = b
                                audioUrl = u
                            }
                        }
                    }

                    val videoStreams = json.optJSONArray("videoStreams")
                    if (videoStreams != null) {
                        for (i in 0 until videoStreams.length()) {
                            val f = videoStreams.getJSONObject(i)
                            val h = f.optInt("height", 0)
                            val u = f.optString("url", "")
                            if (u.isNotBlank() && h > 0) {
                                qualities.add(VideoQuality("${h}p", h, u, true))
                                if (h > videoHeight) {
                                    videoHeight = h
                                    videoUrl = u
                                }
                            }
                        }
                    }

                    if (audioUrl != null || videoUrl != null) {
                        sb.append("piped 성공: $instance\n")
                        return@withContext StreamResult(
                            videoUrl = videoUrl,
                            audioUrl = audioUrl,
                            muxedUrl = null,
                            title = title,
                            channelName = author,
                            description = desc,
                            debug = sb.toString(),
                            subtitles = emptyList(),
                            qualities = qualities.sortedByDescending { it.height },
                            audioUrlBest = audioUrl,
                            isLive = false
                        )
                    }
                    sb.append("piped $instance: URL 없음\n")
                } catch (e: Exception) {
                    sb.append("piped $instance: ${e.message?.take(60)}\n")
                }
            }
            StreamResult(null, null, null, "", "", "", sb.toString())
        }
}
