package com.example.myplayer

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.StreamInfo

data class SubtitleTrack(
    val languageCode: String,
    val displayName: String,
    val url: String,
    val isAutoGenerated: Boolean
)

data class VideoQuality(
    val label: String,
    val height: Int,
    val url: String,
    val isVideoOnly: Boolean
)

object YouTubeStream {

    private const val TAG = "YouTubeStream"

    data class StreamResult(
        val videoUrl: String?,
        val audioUrl: String?,
        val muxedUrl: String?,
        val title: String,
        val channelName: String,
        val description: String,
        val debug: String,
        val subtitles: List<SubtitleTrack> = emptyList(),
        val qualities: List<VideoQuality> = emptyList(),
        val audioUrlBest: String? = null,
        val isLive: Boolean = false
    ) {
        val hasAny: Boolean
            get() = muxedUrl != null || videoUrl != null || audioUrl != null
    }

    suspend fun extract(videoId: String): StreamResult = withContext(Dispatchers.IO) {
        val sb = StringBuilder()

        // ★ 1차: Invidious/Piped 직접 (NewPipe 우회)
        try {
            val direct = YouTubeApiHelper.extractStream(videoId)
            if (direct.audioUrl != null || direct.videoUrl != null || direct.muxedUrl != null) {
                sb.append("direct: ${direct.source}\n")
                return@withContext StreamResult(
                    videoUrl = direct.videoUrl,
                    audioUrl = direct.audioUrl,
                    muxedUrl = direct.muxedUrl,
                    title = direct.title,
                    channelName = direct.channel,
                    description = "",
                    debug = sb.toString(),
                    audioUrlBest = direct.audioUrl
                )
            }
            sb.append("direct fail\n")
        } catch (e: Exception) {
            sb.append("direct err: ${e.message?.take(60)}\n")
        }

        // ★ 2차: NewPipe (폴백)
        try {
            val ctx = MyApp.instance.applicationContext
            val hasCookie = YouTubeCookieManager.hasCookie(ctx)
            val cookieLen = YouTubeCookieManager.load(ctx).length
            sb.append("cookie: has=$hasCookie len=$cookieLen\n")
        } catch (_: Exception) {}

        try {
            try { NewPipe.init(DownloaderImpl()) } catch (_: Exception) {}

            val url = "https://www.youtube.com/watch?v=$videoId"
            var info: StreamInfo? = null
            var lastErr: Exception? = null
            for (attempt in 0 until 3) {
                try {
                    info = StreamInfo.getInfo(ServiceList.YouTube, url)
                    if (info != null) break
                } catch (e: Exception) {
                    lastErr = e
                    sb.append("newpipe try ${attempt + 1} FAIL: ${e.message?.take(60)}\n")
                    if (attempt < 2) {
                        try { Thread.sleep(800L * (attempt + 1)) } catch (_: Exception) {}
                    }
                }
            }

            if (info == null) {
                sb.append("newpipe FAIL final\n")
                return@withContext StreamResult(null, null, null, "", "", "", sb.toString())
            }

            val title = info.name ?: ""
            val channelName = try { info.uploaderName ?: "" } catch (_: Exception) { "" }
            val description = try { info.description?.content ?: "" } catch (_: Exception) { "" }

            val bestAudio = try {
                info.audioStreams.filter { it.isUrl }.maxByOrNull { it.averageBitrate }?.content
            } catch (_: Exception) { null }
            val muxed = info.videoStreams.firstOrNull { !it.isVideoOnly && it.isUrl }

            val qualities = mutableListOf<VideoQuality>()
            try {
                for (stream in info.videoStreams) {
                    if (!stream.isUrl) continue
                    val height = try { stream.resolution } catch (_: Exception) { "" }
                    val h = height.replace("p", "").toIntOrNull() ?: continue
                    if (h < 144) continue
                    qualities.add(VideoQuality("${h}p", h, stream.content, stream.isVideoOnly))
                }
            } catch (_: Exception) {}

            val subs = mutableListOf<SubtitleTrack>()
            try {
                info.subtitles?.forEach { s ->
                    val lang = s.languageTag ?: return@forEach
                    val display = s.displayLanguageName ?: lang
                    val u = s.content ?: return@forEach
                    val auto = try { s.isAutoGenerated } catch (_: Exception) { false }
                    subs.add(SubtitleTrack(lang, display, u, auto))
                }
            } catch (_: Exception) {}

            if (muxed != null) {
                return@withContext StreamResult(
                    null, null, muxed.content, title, channelName, description,
                    sb.toString(), subs, qualities, bestAudio
                )
            }
            val audio = try {
                info.audioStreams.filter { it.isUrl }.maxByOrNull { it.averageBitrate }
            } catch (_: Exception) { null }
            if (audio != null) {
                return@withContext StreamResult(
                    null, audio.content, null, title, channelName, description,
                    sb.toString(), subs, qualities, bestAudio
                )
            }
        } catch (e: Exception) {
            sb.append("newpipe outer err: ${e.message?.take(60)}\n")
        }

        StreamResult(null, null, null, "", "", "", sb.toString())
    }
}
